### PR TITLE
Added middleware example

### PR DESCRIPTION
**Pull request by martinssipenko**

### CODE REVIEW

**Comment by stefanzweifel** [comment]
:+1: for your middleware example. Helped me a lot.

**Comment by billmn** [comment]
Can be merged now that a release for L5 is tagged?

**Comment by GrahamCampbell** [comment]
Yeh, I'll get to it later. I want to partially rewrite the docs to make them clearer, but have no time right now. I will get to this at some point, promise. :)

**Comment by GrahamCampbell** [comment]
Laravel 5.1 now has middlewares that support parameters like filters used to. We're going to ship with a default middleware instead of a default filter in 4.0. See #28.

**Pull request closed without merging**
