### PR TITLE
Upgrading to Laravel 5.6

### PR DESCRIPTION
**Pull request by stephandesouza**
- [x] Changed illuminate/* requirements in composer.json
- [x] Added Travis tests
  - [x] Drop Laravel 5.6 on PHP 7.0
  - [x] See whats happen with [orchestra/testbench^3.6](https://github.com/orchestral/testbench)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs.

**Comment by luizjrdeveloper** [comment]
@GrahamCampbell You said that in two weeks, they are already completing, something new?

> In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs.
[https://github.com/GrahamCampbell/Laravel-Throttle/pull/76#issuecomment-364654566](url)

**Comment by stephandesouza** [comment]
[orchestra/testbench^3.6](https://github.com/orchestral/testbench) now accepts Laravel 5.6, i guess is time to rebuild the Travis. :(

**Comment by jdavidbakr** [comment]
@GrahamCampbell - any chance we can at least get this pull request merged so this package can work in 5.6?  Is there more complexity to the update than this provides?

**Comment by GrahamCampbell** [comment]
Thanks. I'll update this package shortly.

**Pull request closed without merging**
